const getImage = (id, name) => {
  switch (name) {
    case "1.png":
      switch (id) {
        case 1:
          return require(`../product_image/1/1.png`);
        case 2:
          return require(`../product_image/2/1.png`);
        case 3:
          return require(`../product_image/3/1.png`);
        case 4:
          return require(`../product_image/4/1.png`);
        case 5:
          return require(`../product_image/5/1.png`);
        case 6:
          return require(`../product_image/6/1.png`);
        case 7:
          return require(`../product_image/7/1.png`);
        case 8:
          return require(`../product_image/8/1.png`);
        case 9:
          return require(`../product_image/9/1.png`);
        case 10:
          return require(`../product_image/10/1.png`);
        case 11:
          return require(`../product_image/11/1.png`);
        case 12:
          return require(`../product_image/12/1.png`);
        case 13:
          return require(`../product_image/13/1.png`);
        case 14:
          return require(`../product_image/14/1.png`);
        case 15:
          return require(`../product_image/15/1.png`);
        case 16:
          return require(`../product_image/16/1.png`);
        case 17:
          return require(`../product_image/17/1.png`);
        case 18:
          return require(`../product_image/18/1.png`);
        case 19:
          return require(`../product_image/19/1.png`);
        case 20:
          return require(`../product_image/20/1.png`);
        case 21:
          return require(`../product_image/21/1.png`);
        case 22:
          return require(`../product_image/22/1.png`);
        case 23:
          return require(`../product_image/23/1.png`);
        case 24:
          return require(`../product_image/24/1.png`);
        case 25:
          return require(`../product_image/25/1.png`);
        case 26:
          return require(`../product_image/26/1.png`);
        case 27:
          return require(`../product_image/27/1.png`);
        case 28:
          return require(`../product_image/28/1.png`);
        case 29:
          return require(`../product_image/29/1.png`);
        case 30:
          return require(`../product_image/30/1.png`);
        case 31:
          return require(`../product_image/31/1.png`);
        case 32:
          return require(`../product_image/32/1.png`);
        case 33:
          return require(`../product_image/33/1.png`);
        case 34:
          return require(`../product_image/34/1.png`);
        case 35:
          return require(`../product_image/35/1.png`);
        case 36:
          return require(`../product_image/36/1.png`);
        case 37:
          return require(`../product_image/37/1.png`);
        case 38:
          return require(`../product_image/38/1.png`);
        case 39:
          return require(`../product_image/39/1.png`);
        case 40:
          return require(`../product_image/40/1.png`);
        case 41:
          return require(`../product_image/41/1.png`);
        case 42:
          return require(`../product_image/42/1.png`);
        case 43:
          return require(`../product_image/43/1.png`);
        case 44:
          return require(`../product_image/44/1.png`);
        case 45:
          return require(`../product_image/45/1.png`);
        case 46:
          return require(`../product_image/46/1.png`);
        case 47:
          return require(`../product_image/47/1.png`);
        case 48:
          return require(`../product_image/48/1.png`);
        case 49:
          return require(`../product_image/49/1.png`);
        case 50:
          return require(`../product_image/50/1.png`);
      }
    case "2.png":
      switch (id) {
        case 1:
          return require(`../product_image/1/2.png`);
        case 2:
          return require(`../product_image/2/2.png`);
        case 3:
          return require(`../product_image/3/2.png`);
        case 4:
          return require(`../product_image/4/2.png`);
        case 5:
          return require(`../product_image/5/2.png`);
        case 6:
          return require(`../product_image/6/2.png`);
        case 7:
          return require(`../product_image/7/2.png`);
        case 8:
          return require(`../product_image/8/2.png`);
        case 9:
          return require(`../product_image/9/2.png`);
        case 10:
          return require(`../product_image/10/2.png`);
        case 11:
          return require(`../product_image/11/2.png`);
        case 12:
          return require(`../product_image/12/2.png`);
        case 13:
          return require(`../product_image/13/2.png`);
        case 14:
          return require(`../product_image/14/2.png`);
        case 15:
          return require(`../product_image/15/2.png`);
        case 16:
          return require(`../product_image/16/2.png`);
        case 17:
          return require(`../product_image/17/2.png`);
        case 18:
          return require(`../product_image/18/2.png`);
        case 19:
          return require(`../product_image/19/2.png`);
        case 20:
          return require(`../product_image/20/2.png`);
        case 21:
          return require(`../product_image/21/2.png`);
        case 22:
          return require(`../product_image/22/2.png`);
        case 23:
          return require(`../product_image/23/2.png`);
        case 24:
          return require(`../product_image/24/2.png`);
        case 25:
          return require(`../product_image/25/2.png`);
        case 26:
          return require(`../product_image/26/2.png`);
        case 27:
          return require(`../product_image/27/2.png`);
        case 28:
          return require(`../product_image/28/2.png`);
        case 29:
          return require(`../product_image/29/2.png`);
        case 30:
          return require(`../product_image/30/2.png`);
        case 31:
          return require(`../product_image/31/2.png`);
        case 32:
          return require(`../product_image/32/2.png`);
        case 33:
          return require(`../product_image/33/2.png`);
        case 34:
          return require(`../product_image/34/2.png`);
        case 35:
          return require(`../product_image/35/2.png`);
        case 36:
          return require(`../product_image/36/2.png`);
        case 37:
          return require(`../product_image/37/2.png`);
        case 38:
          return require(`../product_image/38/2.png`);
        case 39:
          return require(`../product_image/39/2.png`);
        case 40:
          return require(`../product_image/40/2.png`);
        case 41:
          return require(`../product_image/41/2.png`);
        case 42:
          return require(`../product_image/42/2.png`);
        case 43:
          return require(`../product_image/43/2.png`);
        case 44:
          return require(`../product_image/44/2.png`);
        case 45:
          return require(`../product_image/45/2.png`);
        case 46:
          return require(`../product_image/46/2.png`);
        case 47:
          return require(`../product_image/47/2.png`);
        case 48:
          return require(`../product_image/48/2.png`);
        case 49:
          return require(`../product_image/49/2.png`);
        case 50:
          return require(`../product_image/50/2.png`);
      }
    case "3.png":
      switch (id) {
        case 1:
          return require(`../product_image/1/3.png`);
        case 2:
          return require(`../product_image/2/3.png`);
        case 3:
          return require(`../product_image/3/3.png`);
        case 4:
          return require(`../product_image/4/3.png`);
        case 5:
          return require(`../product_image/5/3.png`);
        case 6:
          return require(`../product_image/6/3.png`);
        case 7:
          return require(`../product_image/7/3.png`);
        case 8:
          return require(`../product_image/8/3.png`);
        case 9:
          return require(`../product_image/9/3.png`);
        case 10:
          return require(`../product_image/10/3.png`);
        case 11:
          return require(`../product_image/11/3.png`);
        case 12:
          return require(`../product_image/12/3.png`);
        case 13:
          return require(`../product_image/13/3.png`);
        case 14:
          return require(`../product_image/14/3.png`);
        case 15:
          return require(`../product_image/15/3.png`);
        case 16:
          return require(`../product_image/16/3.png`);
        case 17:
          return require(`../product_image/17/3.png`);
        case 18:
          return require(`../product_image/18/3.png`);
        case 19:
          return require(`../product_image/19/3.png`);
        case 20:
          return require(`../product_image/20/3.png`);
        case 21:
          return require(`../product_image/21/3.png`);
        case 22:
          return require(`../product_image/22/3.png`);
        case 23:
          return require(`../product_image/23/3.png`);
        case 24:
          return require(`../product_image/24/3.png`);
        case 25:
          return require(`../product_image/25/3.png`);
        case 26:
          return require(`../product_image/26/3.png`);
        case 27:
          return require(`../product_image/27/3.png`);
        case 28:
          return require(`../product_image/28/3.png`);
        case 29:
          return require(`../product_image/29/3.png`);
        case 30:
          return require(`../product_image/30/3.png`);
        case 31:
          return require(`../product_image/31/3.png`);
        case 32:
          return require(`../product_image/32/3.png`);
        case 33:
          return require(`../product_image/33/3.png`);
        case 34:
          return require(`../product_image/34/3.png`);
        case 35:
          return require(`../product_image/35/3.png`);
        case 36:
          return require(`../product_image/36/3.png`);
        case 37:
          return require(`../product_image/37/3.png`);
        case 38:
          return require(`../product_image/38/3.png`);
        case 39:
          return require(`../product_image/39/3.png`);
        case 40:
          return require(`../product_image/40/3.png`);
        case 41:
          return require(`../product_image/41/3.png`);
        case 42:
          return require(`../product_image/42/3.png`);
        case 43:
          return require(`../product_image/43/3.png`);
        case 44:
          return require(`../product_image/44/3.png`);
        case 45:
          return require(`../product_image/45/3.png`);
        case 46:
          return require(`../product_image/46/3.png`);
        case 47:
          return require(`../product_image/47/3.png`);
        case 48:
          return require(`../product_image/48/3.png`);
        case 49:
          return require(`../product_image/49/3.png`);
        case 50:
          return require(`../product_image/50/3.png`);
      }
    case "4.png":
      switch (id) {
        case 1:
          return require(`../product_image/1/4.png`);
        case 2:
          return require(`../product_image/2/4.png`);
        case 3:
          return require(`../product_image/3/4.png`);
        case 4:
          return require(`../product_image/4/4.png`);
        case 5:
          return require(`../product_image/5/4.png`);
        case 6:
          return require(`../product_image/6/4.png`);
        case 7:
          return require(`../product_image/7/4.png`);
        case 8:
          return require(`../product_image/8/4.png`);
        case 9:
          return require(`../product_image/9/4.png`);
        case 10:
          return require(`../product_image/10/4.png`);
        case 11:
          return require(`../product_image/11/4.png`);
        case 12:
          return require(`../product_image/12/4.png`);
        case 13:
          return require(`../product_image/13/4.png`);
        case 14:
          return require(`../product_image/14/4.png`);
        case 15:
          return require(`../product_image/15/4.png`);
        case 16:
          return require(`../product_image/16/4.png`);
        case 17:
          return require(`../product_image/17/4.png`);
        case 18:
          return require(`../product_image/18/4.png`);
        case 19:
          return require(`../product_image/19/4.png`);
        case 20:
          return require(`../product_image/20/4.png`);
        case 21:
          return require(`../product_image/21/4.png`);
        case 22:
          return require(`../product_image/22/4.png`);
        case 23:
          return require(`../product_image/23/4.png`);
        case 24:
          return require(`../product_image/24/4.png`);
        case 25:
          return require(`../product_image/25/4.png`);
        case 26:
          return require(`../product_image/26/4.png`);
        case 27:
          return require(`../product_image/27/4.png`);
        case 28:
          return require(`../product_image/28/4.png`);
        case 29:
          return require(`../product_image/29/4.png`);
        case 30:
          return require(`../product_image/30/4.png`);
        case 31:
          return require(`../product_image/31/4.png`);
        case 32:
          return require(`../product_image/32/4.png`);
        case 33:
          return require(`../product_image/33/4.png`);
        case 34:
          return require(`../product_image/34/4.png`);
        case 35:
          return require(`../product_image/35/4.png`);
        case 36:
          return require(`../product_image/36/4.png`);
        case 37:
          return require(`../product_image/37/4.png`);
        case 38:
          return require(`../product_image/38/4.png`);
        case 39:
          return require(`../product_image/39/4.png`);
        case 40:
          return require(`../product_image/40/4.png`);
        case 41:
          return require(`../product_image/41/4.png`);
        case 42:
          return require(`../product_image/42/4.png`);
        case 43:
          return require(`../product_image/43/4.png`);
        case 44:
          return require(`../product_image/44/4.png`);
        case 45:
          return require(`../product_image/45/4.png`);
        case 46:
          return require(`../product_image/46/4.png`);
        case 47:
          return require(`../product_image/47/4.png`);
        case 48:
          return require(`../product_image/48/4.png`);
        case 49:
          return require(`../product_image/49/4.png`);
        case 50:
          return require(`../product_image/50/4.png`);
      }
    case "5.png":
      switch (id) {
        case 1:
          return require(`../product_image/1/5.png`);
        case 2:
          return require(`../product_image/2/5.png`);
        case 3:
          return require(`../product_image/3/5.png`);
        case 4:
          return require(`../product_image/4/5.png`);
        case 5:
          return require(`../product_image/5/5.png`);
        case 6:
          return require(`../product_image/6/5.png`);
        case 7:
          return require(`../product_image/7/5.png`);
        case 8:
          return require(`../product_image/8/5.png`);
        case 9:
          return require(`../product_image/9/5.png`);
        case 10:
          return require(`../product_image/10/5.png`);
        case 11:
          return require(`../product_image/11/5.png`);
        case 12:
          return require(`../product_image/12/5.png`);
        case 13:
          return require(`../product_image/13/5.png`);
        case 14:
          return require(`../product_image/14/5.png`);
        case 15:
          return require(`../product_image/15/5.png`);
        case 16:
          return require(`../product_image/16/5.png`);
        case 17:
          return require(`../product_image/17/5.png`);
        case 18:
          return require(`../product_image/18/5.png`);
        case 19:
          return require(`../product_image/19/5.png`);
        case 20:
          return require(`../product_image/20/5.png`);
        case 22:
          return require(`../product_image/22/5.png`);
        case 23:
          return require(`../product_image/23/5.png`);
        case 24:
          return require(`../product_image/24/5.png`);
        case 25:
          return require(`../product_image/25/5.png`);
        case 26:
          return require(`../product_image/26/5.png`);
        case 27:
          return require(`../product_image/27/5.png`);
        case 28:
          return require(`../product_image/28/5.png`);
        case 29:
          return require(`../product_image/29/5.png`);
        case 30:
          return require(`../product_image/30/5.png`);
        case 31:
          return require(`../product_image/31/5.png`);
        case 32:
          return require(`../product_image/32/5.png`);
        case 33:
          return require(`../product_image/33/5.png`);
        case 34:
          return require(`../product_image/34/5.png`);
        case 35:
          return require(`../product_image/35/5.png`);
        case 36:
          return require(`../product_image/36/5.png`);
        case 37:
          return require(`../product_image/37/5.png`);
        case 38:
          return require(`../product_image/38/5.png`);
        case 39:
          return require(`../product_image/39/5.png`);
        case 40:
          return require(`../product_image/40/5.png`);
        case 41:
          return require(`../product_image/41/5.png`);
        case 42:
          return require(`../product_image/42/5.png`);
        case 43:
          return require(`../product_image/43/5.png`);
        case 44:
          return require(`../product_image/44/5.png`);
        case 45:
          return require(`../product_image/45/5.png`);
        case 46:
          return require(`../product_image/46/5.png`);
        case 47:
          return require(`../product_image/47/5.png`);
        case 48:
          return require(`../product_image/48/5.png`);
        case 49:
          return require(`../product_image/49/5.png`);
        case 50:
          return require(`../product_image/50/5.png`);
      }
    case "6.png":
      switch (id) {
        case 1:
          return require(`../product_image/1/6.png`);
        case 2:
          return require(`../product_image/2/6.png`);
        case 3:
          return require(`../product_image/3/6.png`);
        case 4:
          return require(`../product_image/4/6.png`);
        case 5:
          return require(`../product_image/5/6.png`);
        case 6:
          return require(`../product_image/6/6.png`);
        case 7:
          return require(`../product_image/7/6.png`);
        case 8:
          return require(`../product_image/8/6.png`);
        case 9:
          return require(`../product_image/9/6.png`);
        case 10:
          return require(`../product_image/10/6.png`);
        case 11:
          return require(`../product_image/11/6.png`);
        case 12:
          return require(`../product_image/12/6.png`);
        case 13:
          return require(`../product_image/13/6.png`);
        case 14:
          return require(`../product_image/14/6.png`);
        case 15:
          return require(`../product_image/15/6.png`);
        case 16:
          return require(`../product_image/16/6.png`);
        case 17:
          return require(`../product_image/17/6.png`);
        case 18:
          return require(`../product_image/18/6.png`);
        case 19:
          return require(`../product_image/19/6.png`);
        case 20:
          return require(`../product_image/20/6.png`);
        case 22:
          return require(`../product_image/22/6.png`);
        case 23:
          return require(`../product_image/23/6.png`);
        case 24:
          return require(`../product_image/24/6.png`);
        case 25:
          return require(`../product_image/25/6.png`);
        case 26:
          return require(`../product_image/26/6.png`);
        case 27:
          return require(`../product_image/27/6.png`);
        case 28:
          return require(`../product_image/28/6.png`);
        case 29:
          return require(`../product_image/29/6.png`);
        case 30:
          return require(`../product_image/30/6.png`);
        case 31:
          return require(`../product_image/31/6.png`);
        case 32:
          return require(`../product_image/32/6.png`);
        case 33:
          return require(`../product_image/33/6.png`);
        case 34:
          return require(`../product_image/34/6.png`);
        case 35:
          return require(`../product_image/35/6.png`);
        case 36:
          return require(`../product_image/36/6.png`);
        case 37:
          return require(`../product_image/37/6.png`);
        case 38:
          return require(`../product_image/38/6.png`);
        case 39:
          return require(`../product_image/39/6.png`);
        case 40:
          return require(`../product_image/40/6.png`);
        case 41:
          return require(`../product_image/41/6.png`);
        case 42:
          return require(`../product_image/42/6.png`);
        case 43:
          return require(`../product_image/43/6.png`);
        case 44:
          return require(`../product_image/44/6.png`);
        case 45:
          return require(`../product_image/45/6.png`);
        case 46:
          return require(`../product_image/46/6.png`);
        case 47:
          return require(`../product_image/47/6.png`);
        case 48:
          return require(`../product_image/48/6.png`);
        case 49:
          return require(`../product_image/49/6.png`);
        case 50:
          return require(`../product_image/50/6.png`);
    }
  }
};
export { getImage };
